### ISSUE TITLE
Id is a required field in schema, but is documented as optional

### ISSUE THREAD

**Issue by theetrain** [project-colophon/schema#6]
### I'm submitting a...

- [x] Bug report  
- [x] Documentation issue or request

## Detailed Description

[Schema 1.1](https://github.com/project-colophon/schema/blob/84ae84b4b4f42dbfb8a73444b9afe6432c7991a7/schema/1.1/README.md#colophonjson) shows `id` as an optional entry, but it's required according to the schema:

https://github.com/project-colophon/schema/blob/84ae84b4b4f42dbfb8a73444b9afe6432c7991a7/schema/1.1/schema.json#L12-L18

**Comment by ahmadnassri** [comment]
resolved in #10
